# Generated by Django 5.0 on 2023-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='team_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='games',
            name='team_2',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
