# Generated by Django 5.0 on 2023-12-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_team_remove_ranking_team_name_ranking_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ('rank',), 'verbose_name_plural': 'rankings'},
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='ranking',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='ranking.team'),
        ),
    ]
