# Generated by Django 5.0 on 2023-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_alter_ranking_options_remove_ranking_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
